name: Run Gameweek Scores

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC every day

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust as needed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Use 'pip' instead of 'pip3'

      - name: Run gameweek_scores.py
        run: |
          python /fantasy_prem/gameweek_scores.py  # Adjust path if needed
